Cargo.toml, src/io/mod.rs, src/io/parquet.rs, src/lib.rs
related issue: #37
This PR have two things needed to discussion now:
1. The `flush_and_close` interface. [In parquet, it used to write footer.](https://arrow.apache.org/rust/parquet/arrow/index.html#example-of-writing-arrow-record-batch-to-parquet-file:~:text=//%20writer%20must%20be%20closed%20to%20write%20footer%0A%20writer.close().unwrap()%3B) Not sure whether it can be a general interface in FileAppender. But seems it can't be avoid if we reuse [parquet](https://arrow.apache.org/rust/parquet/arrow/index.html.).
2. Can we cancel arrow_schema optional? Because we need to use it in parquet appender. 
@liurenjie1024 @Xuanwo
=> feat: Add support for writing parquet

Cargo.toml, src/io/location_generator.rs, src/io/mod.rs, src/types/in_memory.rs, src/types/on_disk/manifest_file.rs
To impl #38, we need to implement a data file location generator first. It used to generate the relpath of a data file used by opendal.
This PR implement a simple version of it.
=> feat: support data file location generator

src/io/data_file_writer.rs, src/io/mod.rs, src/io/parquet/write.rs
This PR implement #38 in a simple version.
Due to https://docs.rs/parquet/latest/parquet/arrow/async_writer/struct.AsyncArrowWriter.html didn't expose interface to track writen bytes, we can't track it. I'm investigate a way to solve it, such as a track wrapper of writer like https://docs.rs/parquet/latest/parquet/file/writer/struct.TrackedWrite.html#method.write.
Any suggestions? @Xuanwo @liurenjie1024
=> feat: implement data writer

src/io/mod.rs, src/io/task_writer.rs, src/table.rs
This PR provide the task writer interface disscussed in #74.
We didn't support partition now, so it basically a wrapper of data file writer.
=> feat: support task writer

src/table.rs, src/types/in_memory.rs, src/types/on_disk/manifest_file.rs, src/types/on_disk/manifest_list.rs
This pr rename some data structures to better align to iceberg spec.
1. Add a struct `ManifestList`
2. Rename `ManifestList` to `ManifestListEntry`
3. Add a struct `ManifestFile`
4. Rename `ManifestFile` to `ManifestEntry`
=> fix: Rename some data structures.

src/io/task_writer.rs
Original way to predict partition write is uncorrect🥵.
=> fix: uncorrect partition write predict

src/table.rs
> It seems unreasonable to me to have a mutable reference to create a task_writer, how about make the task_id an atomic variable?
>> Do we prepare make it be a shared-object. Otherwise, maybe RefCell🤔?
>>>Both LGTM, but I guess RefCell can't be Send
```
/// Return a task writer used to write data into table.
pub async fn task_writer(&mut self) -> Result<TaskWriter> {
...
self.task_id += 1;
Ok(task_writer)
}
```
So this PR use atomic usize instead of usize for task_id, make task_writer() to use imutable reference.
=> feat: make task_writer to use imutable reference

src/types/in_memory.rs, src/types/on_disk/partition_spec.rs
=> feat: Ser/de partition spec

Cargo.toml, src/io/data_file_writer.rs, src/types/in_memory.rs, src/types/on_disk/manifest_file.rs, src/types/to_avro.rs
Closes #98 
Removed v1 manifest writer support in this pr. It may take some extra effort to be compatible with both v1 and v2, and currenlty we should focus on v2.  Let's add v1 writer later.
=> Add manifest writer tests

src/types/in_memory.rs, src/types/on_disk/types.rs
Out original serialize way for struct type is wrong. We should serialize it to struct rather than map. This PR fix it and add related test.
And I think I push the commit to wrong place and cause create a branch in here...🥵
=> fix: fix the serialize way of struct value

Cargo.toml, src/lib.rs, src/types/in_memory.rs
- [refactor: replace lazy static to once cell](https://github.com/icelake-io/icelake/commit/3f3bbf5f0b4c0e6d877d03a20393896bdeba0f0f) Once the Lazy  in rustc becomes stable, we can easily migrate.
- [refactor: fix default build](https://github.com/icelake-io/icelake/commit/5daae018e1d4fa058054568edf173ea518ea42b2) Fixed the error that occurred by default, indicating that there was no task writer.
=> refactor: replace lazy static to once cell 

icelake/src/types/to_arrow.rs
If we return ArrowError, it will cause user have to depend on arrow_schema sometimes. 
And I find that implementation of to_arrow always return Ok(), can we directly implement `from` rather than `try_from`?
=> refactor: return Error instaed of ArrowError for to_arrow

icelake/src/io/task_writer.rs
I find that task writer don't need to return `HashMap<StructValue,DataFile>`. 
User will use it like following and it probably don't need to know the partition details.
```
let table = create_table();
let task_writer = table.task_writer();
// TaskWriter partition for user, they don't need to know the details.
task_writer.writer(records);
let res = task_writer.close();
let transaction = transaction::new(&mut table);
// Just pass the result to transaction.
transaction.append_datafile(res);
transaction.commit();
```
=> fix: return Vec<Datafile> instead of HashMap

icelake/Cargo.toml, icelake/src/types/in_memory.rs, icelake/src/types/on_disk/types.rs
This PR:
1. refactor StructValue to make it support optional field.
2. Use a more compact way to store the StructValue.
3. Add a StructValueBuilder
=> refactor: refine StructValue

icelake/src/types/in_memory.rs, icelake/src/types/on_disk/manifest_file.rs
=> feat: Expose methods for ser/de data file

Cargo.toml, icelake/Cargo.toml, icelake/src/config.rs, icelake/src/io/data_file_writer.rs, icelake/src/io/task_writer.rs, icelake/src/lib.rs, icelake/src/table.rs
=> feat: Introduce table config

icelake/src/types/transform/mod.rs
RisingWave requires `icelake::io::task_writer::TaskWriter` can be sent. cc @ZENOTME 
https://github.com/risingwavelabs/risingwave/blob/6b6f7177ea58d1ce4aab0ade1985471bd1c525cc/src/connector/src/sink/iceberg.rs#L365
=> require `Send` for `TransformFunction`

.github/workflows/ci.yml, Cargo.toml, icelake/src/io/data_file_writer.rs, icelake/tests/utils/mod.rs, icelake/tests/utils/poetry.rs, testdata/docker/spark-script/spark-connect-server.sh
Fix the bug in split offsets.
Close #160
=> chore: Upgrade arrow to 46

Cargo.toml, icelake/Cargo.toml, icelake/src/catalog/rest.rs, icelake/src/error.rs, icelake/src/lib.rs, icelake/src/table.rs, icelake/tests/insert_tests.rs, icelake/tests/rest_catalog_tests.rs, icelake/tests/utils/containers.rs, icelake/tests/utils/docker.rs, icelake/tests/utils/mod.rs, rest_api/src/apis/catalog_api_api.rs, testdata/docker/iceberg-rest/docker-compose.yaml, testdata/docker/spark-script/spark-connect-server2.sh
Close #175 
1. Implement list tables api.
2. Use docker compose rather testcontainers to setup test. I realized that in fact we can run docker compose in parallel and avoid confliction.
3. Setup test framework.
=> feat: Implement rest catalog tables and add test framework

Cargo.toml, icelake/Cargo.toml, icelake/src/catalog/rest.rs, icelake/src/error.rs, icelake/src/table.rs, icelake/src/types/on_disk/mod.rs, icelake/src/types/on_disk/table_metadata.rs, icelake/tests/rest_catalog_tests.rs, icelake/tests/utils/mod.rs, rest_api/src/apis/catalog_api_api.rs, testdata/docker/spark-script/spark-connect-server2.sh
Close #180 
I found that codes generated by openapi has many bugs and difficult to reuse. I'll remove them in following pr.
=> feat: Introduce load table api

Cargo.toml
The crates dependencies are changed frequently recently (especially arrow). It's better to release a new version.
=> chore: prepare version 0.0.10.

icelake/src/catalog/rest.rs, icelake/src/catalog/storage.rs, icelake/src/io/data_file_writer.rs, icelake/src/io/mod.rs, icelake/src/io/position_delete_writer.rs, icelake/src/io/rolling_writer.rs, icelake/src/io/task_writer.rs, icelake/src/types/in_memory.rs
This PR only support the writer write into a file, we also need more high level writer:
1. partition writer: split the delete op into different partition. 
2. sort writer: sort the delete op in the same partition. (This is optional, user can choose to use writer in this PR directly if they have sorted the op).
They will be completed later.
=> feat: support position delete writer

Cargo.toml, icelake/Cargo.toml, icelake/src/io/task_writer.rs, icelake/src/types/mod.rs, icelake/src/types/partition_splitter.rs, icelake/tests/rest_catalog_tests.rs
After we introduce more writer, we need to reuse partition logic. This PR seperate the partition logic by introduce a PartitionSplitter. We can call the interface in it to split the record batch into multiple group.
`fn split_by_partition(batch) -> HashMap<OwnedRow,batch>`
=> refactor: support PartitionSplitter

icelake/examples/read_iceberg_table.rs, icelake/src/catalog/io.rs, icelake/src/catalog/mod.rs, icelake/src/catalog/rest.rs, icelake/src/catalog/storage.rs, icelake/src/table.rs
This PR adds a operator creator to allow users to reuse storage catalog without adapt to iceberg io config.
A new catalog called `IcebergStorageCatalog` has been added to make it more clear that it accepts iceberg's config.
---
We could make this part better in the future via opendal's own config.
=> feat: Allow reuse storage catalog

icelake/src/transaction.rs, icelake/src/types/on_disk/manifest_list.rs
When the table was just created there is only one snapshot and it doesn't have any parent.
=> make `parent_snapshot_id` optional in `ManifestListWriter`

Cargo.toml, icelake/src/config.rs, icelake/src/io/appender/rolling_writer.rs, icelake/tests/scan_test.rs, icelake/tests/utils/test_generator.rs
As in https://github.com/risingwavelabs/risingwave/issues/13048#issuecomment-1780572388, enable bloom fliter may cause huge memory cost. So let's disable by default.
=> feat: disable bloom fliter by default

icelake/src/io/appender/prometheus.rs
Remove the metrics register work in WritePromethehusLayer. We should leave the register of metrics to the user to avoid duplicate registers.
=> refactor: refactor WritePromethehusLayer to support metrics

icelake/src/types/arrow/to_arrow.rs
iceberg `time` type has microsecond precision, the corresponding arrow type should be [`Time64MicrosecondType`](https://docs.rs/arrow/48.0.0/arrow/datatypes/struct.Time64MicrosecondType.html) whose [`DataType`](https://docs.rs/arrow/48.0.0/arrow/datatypes/enum.DataType.html#) is `DataType::Time64(TimeUnit::Microsecond)`
=> fix convert from iceberg type to arrow type

.github/workflows/ci_typos.yml, icelake/src/catalog/io.rs, icelake/src/catalog/mod.rs, icelake/src/catalog/prometheus.rs, icelake/src/catalog/rest.rs, icelake/src/catalog/storage.rs, icelake/src/error.rs, icelake/src/io/append_only_writer.rs, icelake/src/io/appender/mod.rs, icelake/src/io/file_writer/data_file_writer.rs, icelake/src/io/file_writer/equality_delete_writer.rs, icelake/src/io/file_writer/equality_delta_writer.rs, icelake/src/io/file_writer/position_delete_writer.rs, icelake/src/io/location_generator.rs, icelake/src/io/mod.rs, icelake/src/io/parquet/write.rs, icelake/src/io/writer_builder.rs, icelake/src/lib.rs, icelake/src/types/in_memory.rs, icelake/src/types/mod.rs, icelake/src/types/on_disk/partition_spec.rs, icelake/src/types/on_disk/value.rs, icelake/src/types/partition_splitter.rs, icelake/src/types/to_avro.rs, icelake/tests/delta_test.rs, icelake/tests/insert_compact_test.rs, icelake/tests/insert_tests.rs, icelake/tests/utils/test_generator.rs
This PR
1. clear dead code
2. rename task writer to append only writer
3. separate location generator out to append builder
I find `#[allow(dead_code)] in lib will let us miss lots of dead code in the whole codebase. So I moved it to the type crate and catalog crate.
=> refactor: refactor writer

icelake/src/io/append_only_writer.rs, icelake/src/io/file_writer/equality_delta_writer.rs, icelake/src/io/upsert_writer.rs, icelake/src/table.rs, icelake/src/types/partition_splitter.rs
Remove redundant code between EqualityDeleteWriter and PartitionSplitter.
=> refactor: separate out column extractor of partition splitter

icelake/src/types/arrow/to_arrow.rs
I think in most cases arrow Binary type is enough for iceberg Binary type. Just like String type, we use Utf8 instead of LargeUtf8.
=> fix: convert iceberg binary to arrow binary

Cargo.toml, icelake/src/types/to_avro.rs
Upstream Avro has fixed the missing custom attribute so we can switch back to upstream avro now
=> fix: use upstream avro

Cargo.toml
The input param ArrowAsyncWriter changes since 51. https://docs.rs/parquet/51.0.0/parquet/arrow/async_writer/struct.AsyncArrowWriter.html#method.try_new
So I think for now we only can support arrow version >= 51
=> fix: upgrade arrow-* parquet
